### ISSUE TITLE
Fix: env0 help command upgrade

### ISSUE THREAD

**Issue by omryhay1** [env0/env0-client-integrations#43]
- usage shows `env0 deploy -k <apiKey>` , instead of `env0 command` 
- Not all commands have the same flags, approve and cancel have different flags, configure does not have flags. it should show the correct usage.
- In env0 help, change cancel description to be Cancels a deployment that is pending approval (Change the "an" to "a")

**Comment by AdityaSharma911** [comment]
Can I work on this issue?
